INSERT INTO TUTORIALS (ID,TITLE,DESCRIPTION,PUBLISHED) VALUES(1,'Spring Tutorial 1','Tut#1 Desc',FALSE);
INSERT INTO TUTORIALS (ID,TITLE,DESCRIPTION,PUBLISHED) VALUES(2,'Spring Data JPA 2','Tut#2 Desc',FALSE);
INSERT INTO TUTORIALS (ID,TITLE,DESCRIPTION,PUBLISHED) VALUES(3,'H2 DB','Tut#3 Desc',FALSE);
INSERT INTO TUTORIALS (ID,TITLE,DESCRIPTION,PUBLISHED) VALUES(4,'Spring DB CRUD with JPA','Tut#4 Desc',FALSE);

INSERT INTO TUTOR(ID,TUTORIAL_ID,FIRSTNAME,LASTNAME) VALUES(1,2,'Ramesh','Fadatare');
INSERT INTO TUTOR(ID,TUTORIAL_ID,FIRSTNAME,LASTNAME) VALUES(2,4,'John','Doe');
INSERT INTO STUDENT(ID,FIRSTNAME,LASTNAME) VALUES(1,'Tom','Cruise');
INSERT INTO STUDENT_TUTORIAL(STUDENT_ID,TUTORIAL_ID) VALUES(1,4);